package proyecto_multitransportes;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author User
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        Background = new javax.swing.JPanel();
        user = new javax.swing.JLabel();
        usertxt = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        password = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jSeparator2 = new javax.swing.JSeparator();
        Logo = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();
        inicio1 = new javax.swing.JLabel();
        inicio_panel = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        entrar = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        Background.setBackground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        user.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        user.setForeground(new java.awt.Color(24, 87, 44));
        user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        user.setText("USUARIO");
        Background.add(user, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 340, 50));

        usertxt.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        usertxt.setForeground(new java.awt.Color(204, 204, 204));
        usertxt.setText("Ingrese nombre de usuario");
        usertxt.setBorder(null);
        usertxt.setSelectionColor(new java.awt.Color(24, 87, 44));
        usertxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usertxtActionPerformed(evt);
            }
        });
        Background.add(usertxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 340, 40));

        jSeparator1.setForeground(new java.awt.Color(24, 87, 44));
        Background.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 300, 10));

        password.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        password.setForeground(new java.awt.Color(24, 87, 44));
        password.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        password.setText("CONTRASEÑA");
        Background.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 340, 50));

        jPasswordField1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jPasswordField1.setForeground(new java.awt.Color(204, 204, 204));
        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.setBorder(null);
        jPasswordField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jPasswordField1.setSelectionColor(new java.awt.Color(24, 87, 44));
        Background.add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 340, 30));

        jSeparator2.setForeground(new java.awt.Color(24, 87, 44));
        Background.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 300, 10));

        Logo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/logo2 (1).png"))); // NOI18N
        Logo.setMaximumSize(new java.awt.Dimension(670, 470));
        Logo.setMinimumSize(new java.awt.Dimension(670, 470));
        Logo.setPreferredSize(new java.awt.Dimension(670, 470));
        Background.add(Logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, -1));

        Fondo.setBackground(new java.awt.Color(0, 153, 0));
        Fondo.setForeground(new java.awt.Color(0, 168, 78));
        Fondo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo/background 2 (1).png"))); // NOI18N
        Fondo.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Background.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 0, 400, 500));

        inicio1.setFont(new java.awt.Font("Roboto", 1, 24)); // NOI18N
        inicio1.setForeground(new java.awt.Color(255, 255, 255));
        inicio1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inicio1.setText("INICIAR SESIÓN");
        Background.add(inicio1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 340, 50));

        inicio_panel.setBackground(new java.awt.Color(87, 154, 66));
        inicio_panel.setForeground(new java.awt.Color(0, 102, 51));

        javax.swing.GroupLayout inicio_panelLayout = new javax.swing.GroupLayout(inicio_panel);
        inicio_panel.setLayout(inicio_panelLayout);
        inicio_panelLayout.setHorizontalGroup(
            inicio_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
        );
        inicio_panelLayout.setVerticalGroup(
            inicio_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        Background.add(inicio_panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, -1));

        jPanel1.setBackground(new java.awt.Color(87, 154, 66));
        jPanel1.setForeground(new java.awt.Color(0, 102, 51));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        entrar.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        entrar.setForeground(new java.awt.Color(255, 255, 255));
        entrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        entrar.setText("ENTRAR");
        entrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(entrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 180, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(entrar, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                .addContainerGap())
        );

        Background.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 180, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usertxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usertxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usertxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Logo;
    private javax.swing.JLabel entrar;
    private javax.swing.JLabel inicio1;
    private javax.swing.JPanel inicio_panel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel password;
    private javax.swing.JLabel user;
    private javax.swing.JTextField usertxt;
    // End of variables declaration//GEN-END:variables
}
