package Main;

import Cajas.MainCajas;
import Catalogos.Proveedores.ViewProveedores;
import Catalogos.Vehiculos.ViewVehiculos;
import Catalogos.Clientes.ViewClientes;
import Catalogos.Conductores.ViewConductores;
import Catalogos.Destinos.ViewDestinos;
import Catalogos.Empleados.ViewEmpleados;
import Facturacion.ViewFactura;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.Socket;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public mainMenu() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Sistema para Empresa Multitransportes Ride Me v1.0");

        try {
            sc = new Socket(HOST, PUERTO);
            entrada = new DataInputStream(sc.getInputStream());
            salida = new DataOutputStream(sc.getOutputStream());

        } catch (IOException ex) {
            System.out.print("¡Error durante el proceso de conexión, revise!");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_facturacion = new javax.swing.JButton();
        btn_cajas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_conductores1 = new javax.swing.JButton();
        btn_proveedores = new javax.swing.JButton();
        btn_vehiculos = new javax.swing.JButton();
        btn_destinos = new javax.swing.JButton();
        btn_clientes = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_empleados = new javax.swing.JButton();
        txt_id = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_facturacion.setBackground(new java.awt.Color(235, 235, 249));
        btn_facturacion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_facturacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/money-cheque-editar.png"))); // NOI18N
        btn_facturacion.setText("Facturación");
        btn_facturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_facturacionActionPerformed(evt);
            }
        });

        btn_cajas.setBackground(new java.awt.Color(235, 235, 249));
        btn_cajas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cajas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/monedas.png"))); // NOI18N
        btn_cajas.setText("Cajas");
        btn_cajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cajasActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        btn_conductores1.setBackground(new java.awt.Color(235, 235, 249));
        btn_conductores1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_conductores1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/volante.png"))); // NOI18N
        btn_conductores1.setText("Catalogo Conductores");
        btn_conductores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conductores1ActionPerformed(evt);
            }
        });

        btn_proveedores.setBackground(new java.awt.Color(235, 235, 249));
        btn_proveedores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_proveedores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/lado-del-camion.png"))); // NOI18N
        btn_proveedores.setText("Catalogo Proveedores");
        btn_proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proveedoresActionPerformed(evt);
            }
        });

        btn_vehiculos.setBackground(new java.awt.Color(235, 235, 249));
        btn_vehiculos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_vehiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/coche-autobus.png"))); // NOI18N
        btn_vehiculos.setText("Catalogo Vehiculos");
        btn_vehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vehiculosActionPerformed(evt);
            }
        });

        btn_destinos.setBackground(new java.awt.Color(235, 235, 249));
        btn_destinos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_destinos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/mundo.png"))); // NOI18N
        btn_destinos.setText("Catalogo Destinos");
        btn_destinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_destinosActionPerformed(evt);
            }
        });

        btn_clientes.setBackground(new java.awt.Color(235, 235, 249));
        btn_clientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/usuarios-alt.png"))); // NOI18N
        btn_clientes.setText("Catalogo Clientes");
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_proveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_clientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btn_conductores1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_vehiculos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_destinos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_conductores1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_vehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_destinos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        btn_salir.setBackground(new java.awt.Color(255, 51, 51));
        btn_salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_empleados.setBackground(new java.awt.Color(235, 235, 249));
        btn_empleados.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_empleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Iconos/usuario.png"))); // NOI18N
        btn_empleados.setText("Catalogo Empleados");
        btn_empleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_empleadosActionPerformed(evt);
            }
        });

        txt_id.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 153), 1, true));
        txt_id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_empleados)
                    .addComponent(btn_facturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_cajas, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel1)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btn_empleados, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_facturacion, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_cajas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
ViewProveedores vp = new ViewProveedores();

    ViewClientes vc = new ViewClientes();
    ViewDestinos mp = new ViewDestinos();
    ViewVehiculos vve = new ViewVehiculos();
    ViewConductores ss = new ViewConductores();
    ViewEmpleados ve = new ViewEmpleados();
    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        vc.setVisible(true);
    }//GEN-LAST:event_btn_clientesActionPerformed

    private void btn_conductores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conductores1ActionPerformed
        ss.setVisible(true);
    }//GEN-LAST:event_btn_conductores1ActionPerformed

    private void btn_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proveedoresActionPerformed
        vp.setVisible(true);
    }//GEN-LAST:event_btn_proveedoresActionPerformed

    private void btn_vehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vehiculosActionPerformed
        vve.setVisible(true);
    }//GEN-LAST:event_btn_vehiculosActionPerformed

    private void btn_destinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_destinosActionPerformed
        mp.setVisible(true);
    }//GEN-LAST:event_btn_destinosActionPerformed
    ViewFactura mj = new ViewFactura();
    private void btn_facturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_facturacionActionPerformed
        mj.setVisible(true);
    }//GEN-LAST:event_btn_facturacionActionPerformed
    MainCajas cm = new MainCajas();

    private static final String HOST = "localhost";
    private static final int PUERTO = 5000;
    private Socket sc;
    private DataInputStream entrada;
    private DataOutputStream salida;
    private String mensajeRecibido = "";
    private String mensajeEnviar = "";


    private void btn_cajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cajasActionPerformed
        try {

            try {

                mensajeEnviar = cm.buscar(Integer.parseInt(txt_id.getText()));
                System.out.print(mensajeEnviar);
                salida.writeUTF(mensajeEnviar);
                mensajeRecibido = entrada.readUTF();
            } catch (IOException ex) {
                Logger.getLogger(mainMenu.class.getName()).log(Level.SEVERE, null, ex);
            }
        } catch (NumberFormatException erro1) {
            JOptionPane.showMessageDialog(null, "Error\n");
        }
    }//GEN-LAST:event_btn_cajasActionPerformed


    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        dispose();
        Login lg = new Login();
        lg.setVisible(true);
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_empleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_empleadosActionPerformed
        ve.setVisible(true);
    }//GEN-LAST:event_btn_empleadosActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cajas;
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_conductores1;
    private javax.swing.JButton btn_destinos;
    private javax.swing.JButton btn_empleados;
    private javax.swing.JButton btn_facturacion;
    private javax.swing.JButton btn_proveedores;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_vehiculos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txt_id;
    // End of variables declaration//GEN-END:variables

    public void esperar() throws IOException {
        salida.writeUTF(mensajeEnviar);
    }
}
