package Main;

import Cajas.MainCajas;
import Catalogos.Proveedores.ViewProveedores;
import Catalogos.Vehiculos.ViewVehiculos;
import Catalogos.Clientes.ViewClientes;
import Catalogos.Conductores.ViewConductores;
import Catalogos.Destinos.ViewDestinos;
import Facturacion.ViewFactura;
import Facturacion.MainFacturas;
import java.util.ArrayList;

/**
 *
 * @author User
 */
public class mainMenu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public mainMenu() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("Sistema para Empresa Multitransportes Ride Me v1.0");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_consultas = new javax.swing.JButton();
        btn_resevaciones = new javax.swing.JButton();
        btn_cajas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        btn_conductores1 = new javax.swing.JButton();
        btn_proveedores = new javax.swing.JButton();
        btn_vehiculos = new javax.swing.JButton();
        btn_destinos = new javax.swing.JButton();
        btn_clientes = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btn_consultas.setBackground(new java.awt.Color(235, 235, 249));
        btn_consultas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_consultas.setText("Empleados");
        btn_consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_consultasActionPerformed(evt);
            }
        });

        btn_resevaciones.setBackground(new java.awt.Color(235, 235, 249));
        btn_resevaciones.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_resevaciones.setText("Reservaciones");
        btn_resevaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resevacionesActionPerformed(evt);
            }
        });

        btn_cajas.setBackground(new java.awt.Color(235, 235, 249));
        btn_cajas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_cajas.setText("Cajas");
        btn_cajas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cajasActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));

        btn_conductores1.setBackground(new java.awt.Color(235, 235, 249));
        btn_conductores1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_conductores1.setText("Catalogo Conductores");
        btn_conductores1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_conductores1ActionPerformed(evt);
            }
        });

        btn_proveedores.setBackground(new java.awt.Color(235, 235, 249));
        btn_proveedores.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_proveedores.setText("Catalogo Proveedores");
        btn_proveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_proveedoresActionPerformed(evt);
            }
        });

        btn_vehiculos.setBackground(new java.awt.Color(235, 235, 249));
        btn_vehiculos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_vehiculos.setText("Catalogo Vehiculos");
        btn_vehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_vehiculosActionPerformed(evt);
            }
        });

        btn_destinos.setBackground(new java.awt.Color(235, 235, 249));
        btn_destinos.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_destinos.setText("Catalogo Destinos");
        btn_destinos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_destinosActionPerformed(evt);
            }
        });

        btn_clientes.setBackground(new java.awt.Color(235, 235, 249));
        btn_clientes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_clientes.setText("Catalogo Clientes");
        btn_clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_clientesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_conductores1, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_destinos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_vehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btn_clientes, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_conductores1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_vehiculos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_destinos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        btn_salir.setBackground(new java.awt.Color(255, 51, 51));
        btn_salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("Salir");
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_resevaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_consultas, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cajas, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(btn_consultas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_resevaciones, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_cajas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
ViewProveedores vp = new ViewProveedores();

    ViewClientes vc = new ViewClientes();
    ViewDestinos mp = new ViewDestinos();
    ViewVehiculos vve = new ViewVehiculos();
    ViewConductores ss = new ViewConductores();
        MainFacturas mj = new MainFacturas();
        ViewFactura wf = new ViewFactura();
    private void btn_clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_clientesActionPerformed
        vc.setVisible(true);
    }//GEN-LAST:event_btn_clientesActionPerformed

    private void btn_conductores1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_conductores1ActionPerformed
        ss.setVisible(true);
    }//GEN-LAST:event_btn_conductores1ActionPerformed

    private void btn_proveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_proveedoresActionPerformed
        vp.setVisible(true);
    }//GEN-LAST:event_btn_proveedoresActionPerformed

    private void btn_vehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_vehiculosActionPerformed
        vve.setVisible(true);
    }//GEN-LAST:event_btn_vehiculosActionPerformed

    private void btn_destinosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_destinosActionPerformed
        mp.setVisible(true);
    }//GEN-LAST:event_btn_destinosActionPerformed

    private void btn_consultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_consultasActionPerformed

    }//GEN-LAST:event_btn_consultasActionPerformed

    private void btn_resevacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resevacionesActionPerformed
        //mj.inicializarCliente();
        wf.setVisible(true);
    }//GEN-LAST:event_btn_resevacionesActionPerformed

MainCajas mcajas = new MainCajas();
    private void btn_cajasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cajasActionPerformed
    //  p.setVisible(true);
      mcajas.buscar();
    }//GEN-LAST:event_btn_cajasActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
        dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cajas;
    private javax.swing.JButton btn_clientes;
    private javax.swing.JButton btn_conductores1;
    private javax.swing.JButton btn_consultas;
    private javax.swing.JButton btn_destinos;
    private javax.swing.JButton btn_proveedores;
    private javax.swing.JButton btn_resevaciones;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_vehiculos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
