package Catalogos.Destinos;
import Catalogos.Destinos.MainDestinos;
import Catalogos.Destinos.MainDestinos;
import Catalogos.Proveedores.MainProveedores;
import javax.swing.JOptionPane;



/**
 *
 * @author User
 */
public class ViewDestinos extends javax.swing.JFrame {

    /**
     * Creates new form Proveedores
     */
    public ViewDestinos() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
    }


    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_destino = new javax.swing.JTextField();
        txt_tiempo = new javax.swing.JTextField();
        chk_especial = new javax.swing.JCheckBox();
        btn_agregar = new javax.swing.JButton();
        btn_editar = new javax.swing.JButton();
        btn_salir = new javax.swing.JButton();
        btn_ver = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_buscar = new javax.swing.JButton();
        cbx_provincias = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_paqueteespe = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_descri = new javax.swing.JTextArea();
        txt_precioespecial = new javax.swing.JTextField();
        txt_regularprecio = new javax.swing.JTextField();
        chk_estado = new javax.swing.JCheckBox();
        txt_id = new javax.swing.JTextField();
        txt_dis = new javax.swing.JTextField();
        cbx_proveedores = new javax.swing.JComboBox<>();
        btn_actu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txt_destino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_destino.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_tiempo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_tiempo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        chk_especial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chk_especial.setText("Paquete Especial");

        btn_agregar.setBackground(new java.awt.Color(235, 235, 249));
        btn_agregar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_agregar.setText("Agregar");
        btn_agregar.setBorder(null);
        btn_agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregarActionPerformed(evt);
            }
        });

        btn_editar.setBackground(new java.awt.Color(235, 235, 249));
        btn_editar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_editar.setText("Editar");
        btn_editar.setBorder(null);
        btn_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editarActionPerformed(evt);
            }
        });

        btn_salir.setBackground(new java.awt.Color(255, 51, 51));
        btn_salir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_salir.setForeground(new java.awt.Color(255, 255, 255));
        btn_salir.setText("Salir");
        btn_salir.setBorder(null);
        btn_salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_salirActionPerformed(evt);
            }
        });

        btn_ver.setBackground(new java.awt.Color(235, 235, 249));
        btn_ver.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_ver.setText("Lista Proveedores ");
        btn_ver.setBorder(null);
        btn_ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_verActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 204));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Descripcion");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Paquete Especial");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio Especial");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(37, 37, 37))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(55, 55, 55)
                .addComponent(jLabel4)
                .addGap(20, 20, 20))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 204));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("DESTINOS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(363, 363, 363)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        btn_buscar.setBackground(new java.awt.Color(235, 235, 249));
        btn_buscar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btn_buscar.setText("Buscar");
        btn_buscar.setBorder(null);
        btn_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscarActionPerformed(evt);
            }
        });

        cbx_provincias.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "null", "San Jose", "Alajuela", "Cartago", "Heredia", "Guanacaste", "Puntarenas", "Limon" }));
        cbx_provincias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbx_provinciasActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(0, 102, 204));
        jPanel3.setForeground(new java.awt.Color(0, 102, 102));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Provincia");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Destino");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Tiempo viaje");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Proveedor");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Precio Regular");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Id");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8))
                .addGap(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addGap(28, 28, 28)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(jLabel10)
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        txt_paqueteespe.setEditable(false);
        txt_paqueteespe.setColumns(20);
        txt_paqueteespe.setRows(5);
        txt_paqueteespe.setWrapStyleWord(true);
        txt_paqueteespe.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txt_paqueteespe);

        txt_descri.setEditable(false);
        txt_descri.setColumns(20);
        txt_descri.setLineWrap(true);
        txt_descri.setRows(5);
        jScrollPane2.setViewportView(txt_descri);

        txt_precioespecial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_precioespecial.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        txt_regularprecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_regularprecio.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_regularprecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_regularprecioActionPerformed(evt);
            }
        });

        chk_estado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        chk_estado.setText("Estado");

        txt_id.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_id.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_idActionPerformed(evt);
            }
        });

        txt_dis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_dis.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txt_dis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_disActionPerformed(evt);
            }
        });

        btn_actu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(184, 184, 184)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_destino, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(txt_tiempo)
                            .addComponent(cbx_provincias, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_regularprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(chk_estado))
                            .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbx_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_actu)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                .addComponent(jScrollPane1))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txt_precioespecial, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chk_especial))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118))
                            .addComponent(txt_dis, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(687, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txt_precioespecial, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(chk_especial)))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(35, 35, 35))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbx_provincias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(txt_destino, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_tiempo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbx_proveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_actu))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_regularprecio, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chk_estado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txt_id, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_ver, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_salir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_editar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(txt_dis, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(81, 81, 81)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(137, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
MainProveedores mp = new MainProveedores();
    MainDestinos md = new MainDestinos();
    private void btn_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editarActionPerformed
md.modificar(Integer.parseInt(txt_id.getText()),  chk_estado.isSelected(), chk_especial.isSelected());
       cbx_proveedores.removeAllItems();
       txt_regularprecio.setText("");
       txt_id.setText("");
        txt_destino.setText("");
        txt_paqueteespe.setText("");
        txt_tiempo.setText("");
        txt_precioespecial.setText("");
        txt_descri.setText("");
        txt_precioespecial.setText("");
        txt_dis.setText("");
        chk_estado.setSelected(false);
        chk_especial.setSelected(false);
    }//GEN-LAST:event_btn_editarActionPerformed

    private void btn_agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregarActionPerformed
         try{
        md.agregar(Integer.parseInt(txt_id.getText()),String.valueOf(cbx_provincias.getSelectedItem()),
                txt_tiempo.getText(), Integer.parseInt(txt_regularprecio.getText()),
                txt_descri.getText(), chk_especial.isSelected(), Integer.parseInt(txt_precioespecial.getText()),
                txt_dis.getText(), chk_estado.isSelected(), Integer.parseInt(String.valueOf(cbx_proveedores.getSelectedItem())), txt_paqueteespe.getText(),
                txt_destino.getText());
       
       cbx_proveedores.removeAllItems();
       txt_regularprecio.setText("");
       txt_id.setText("");
        txt_destino.setText("");
        txt_paqueteespe.setText("");
        txt_tiempo.setText("");
        txt_precioespecial.setText("");
        txt_descri.setText("");
        txt_precioespecial.setText("");
        txt_dis.setText("");
        chk_estado.setSelected(false);
        chk_especial.setSelected(false);
       }catch(NumberFormatException erro1) {
            JOptionPane.showMessageDialog(null, "Error");
       }
    }//GEN-LAST:event_btn_agregarActionPerformed

    private void btn_verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_verActionPerformed
        md.mostrar();
        
    }//GEN-LAST:event_btn_verActionPerformed

    private void btn_salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_salirActionPerformed
 dispose();
    }//GEN-LAST:event_btn_salirActionPerformed

    private void btn_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscarActionPerformed
        try{
            String data[] = new String[11];
         data = md.buscar(Integer.parseInt(txt_id.getText()));
         cbx_provincias.setSelectedItem(data[0]);
          cbx_proveedores.removeAllItems();
          cbx_proveedores.addItem(data[3]);
       txt_regularprecio.setText(data[4]);
        txt_destino.setText(data[1] );
        txt_paqueteespe.setText(data[7]);
        txt_tiempo.setText(data[2] );
        txt_precioespecial.setText(data[8]);
        txt_descri.setText(data[6]);
        txt_dis.setText(data[5]);
         if (String.valueOf(data[9]).compareTo("A") ==0 ) {
chk_estado.setSelected(true);
            }
               if (String.valueOf(data[10]).compareTo("A") ==0 ) {
chk_especial.setSelected(true);
            }
        } catch (NumberFormatException errorbuscar) {
            JOptionPane.showMessageDialog(null, "Error \n");
        }
        
    }//GEN-LAST:event_btn_buscarActionPerformed

    private void txt_regularprecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_regularprecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_regularprecioActionPerformed

    private void txt_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_idActionPerformed

    private void cbx_provinciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbx_provinciasActionPerformed
          String provincia = (String) cbx_provincias.getSelectedItem();
        System.out.print(provincia);
        switch (provincia) {
            case "San Jose":
                txt_destino.setText(md.Chepe[0]);
                txt_tiempo.setText(md.Chepe[1]);
                txt_dis.setText(md.Chepe[6]);
                txt_regularprecio.setText(md.Chepe[2]);
                txt_descri.setText(md.Chepe[3]);
                txt_precioespecial.setText(md.Chepe[5]);
                txt_paqueteespe.setText(md.Chepe[4]);

                break;
            case "Alajuela":
                txt_destino.setText(md.Alaj[0]);
                txt_tiempo.setText(md.Alaj[1]);
                txt_dis.setText(md.Alaj[6]);
                txt_regularprecio.setText(md.Alaj[2]);
                txt_descri.setText(md.Alaj[3]);
                txt_precioespecial.setText(md.Alaj[5]);
                txt_paqueteespe.setText(md.Alaj[4]);
                break;
            case "Heredia":
                txt_destino.setText(md.Here[0]);
                txt_tiempo.setText(md.Here[1]);
                txt_dis.setText(md.Here[6]);
                txt_regularprecio.setText(md.Here[2]);
                txt_descri.setText(md.Here[3]);
                txt_precioespecial.setText(md.Here[5]);
                txt_paqueteespe.setText(md.Here[4]);
                break;

            case "Cartago":
                txt_destino.setText(md.carta[0]);
                txt_tiempo.setText(md.carta[1]);
                txt_dis.setText(md.carta[6]);
                txt_regularprecio.setText(md.carta[2]);
                txt_descri.setText(md.carta[3]);
                txt_precioespecial.setText(md.carta[5]);
                txt_paqueteespe.setText(md.carta[4]);
                break;

            case "Limon":
                txt_destino.setText(md.Lim[0]);
                txt_tiempo.setText(md.Lim[1]);
                txt_dis.setText(md.Lim[6]);
                txt_regularprecio.setText(md.Lim[2]);
                txt_descri.setText(md.Lim[3]);
                txt_precioespecial.setText(md.Lim[5]);
                txt_paqueteespe.setText(md.Lim[4]);
                break;
            case "Puntarenas":
                txt_destino.setText(md.Punta[0]);
                txt_tiempo.setText(md.Punta[1]);
                txt_dis.setText(md.Punta[6]);
                txt_regularprecio.setText(md.Punta[2]);
                txt_descri.setText(md.Punta[3]);
                txt_precioespecial.setText(md.Punta[5]);
                txt_paqueteespe.setText(md.Punta[4]);

                break;
            case "Guanacaste":
                txt_destino.setText(md.Guana[0]);
                txt_tiempo.setText(md.Guana[1]);
                txt_dis.setText(md.Guana[6]);
                txt_regularprecio.setText(md.Guana[2]);
                txt_descri.setText(md.Guana[3]);
                txt_precioespecial.setText(md.Guana[5]);
                txt_paqueteespe.setText(md.Guana[4]);

                break;
            case "null":
                txt_destino.setText("");
                txt_tiempo.setText("");
                txt_dis.setText("");
                txt_regularprecio.setText("");
                txt_paqueteespe.setText("");
                txt_precioespecial.setText("");
                txt_paqueteespe.setText("");
                break;

        }
    }//GEN-LAST:event_cbx_provinciasActionPerformed

    private void txt_disActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_disActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_disActionPerformed

    private void btn_actuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actuActionPerformed
              cbx_proveedores.removeAllItems();
        String[] Nombres = mp.llenarcombobox();
        for (int i = 0; i < Nombres.length; i++) {
            cbx_proveedores.addItem(Nombres[i]);
            System.out.print("end point destinos");
        }
    }//GEN-LAST:event_btn_actuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewDestinos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actu;
    private javax.swing.JButton btn_agregar;
    private javax.swing.JButton btn_buscar;
    private javax.swing.JButton btn_editar;
    private javax.swing.JButton btn_salir;
    private javax.swing.JButton btn_ver;
    private javax.swing.JComboBox<String> cbx_proveedores;
    private javax.swing.JComboBox<String> cbx_provincias;
    private javax.swing.JCheckBox chk_especial;
    private javax.swing.JCheckBox chk_estado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea txt_descri;
    private javax.swing.JTextField txt_destino;
    private javax.swing.JTextField txt_dis;
    private javax.swing.JTextField txt_id;
    private javax.swing.JTextArea txt_paqueteespe;
    private javax.swing.JTextField txt_precioespecial;
    private javax.swing.JTextField txt_regularprecio;
    private javax.swing.JTextField txt_tiempo;
    // End of variables declaration//GEN-END:variables
}
